In [43]:
import pandas as pd

df= pd.read_csv("/Users/sachinmishra/Desktop/Project-1/training/dataset/synthetic_logs.csv")
df.head(10)

,timestamp,source,log_message,target_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status
5,2025-10-09 10:30:31,ModernHR,nova.osapi_compute.wsgi.server [req-f0bffbc3-5...,HTTP Status
6,3/1/2025 19:14,ModernHR,Shard 6 replication task ended in failure,Error
7,10/11/2025 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification
8,2025-02-12 10:42:29,ThirdPartyAPI,nova.compute.claims [req-a07ac654-8e81-416d-bf...,Resource Usage
9,2025-03-30 04:01:45,ModernHR,nova.osapi_compute.wsgi.server [req-2bf7cfee-a...,HTTP Status

In [44]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [45]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [46]:
df[df.target_label=="System Notification"].sample(10)

,timestamp,source,log_message,target_label
160,3/30/2025 11:09,BillingSystem,Disk cleanup completed successfully.,System Notification
2363,10/26/2025 23:44,ModernCRM,Backup ended at 2025-09-19 08:52:02.,System Notification
310,9/17/2025 21:39,AnalyticsEngine,File data_5435.csv uploaded successfully by us...,System Notification
1948,5/14/2025 18:04,ModernCRM,Backup started at 2025-11-23 01:05:16.,System Notification
1824,1/1/2025 18:53,BillingSystem,File data_3868.csv uploaded successfully by us...,System Notification
878,11/10/2025 2:58,AnalyticsEngine,Backup ended at 2025-12-04 02:19:48.,System Notification
837,4/9/2025 8:28,AnalyticsEngine,System reboot initiated by user User876.,System Notification
1207,1/9/2025 22:57,ModernCRM,File data_3277.csv uploaded successfully by us...,System Notification
429,12/20/2025 9:22,ModernCRM,Backup started at 2025-10-12 10:35:15.,System Notification
192,10/19/2025 14:12,BillingSystem,System updated to version 3.7.7.,System Notification

In [47]:
df[df.log_message.str.startswith("System reboot initiated by user")]

,timestamp,source,log_message,target_label
36,11/19/2025 13:14,BillingSystem,System reboot initiated by user User243.,System Notification
92,12/4/2025 21:20,BillingSystem,System reboot initiated by user User471.,System Notification
139,5/8/2025 16:34,ModernHR,System reboot initiated by user User216.,System Notification
140,9/11/2025 8:49,AnalyticsEngine,System reboot initiated by user User639.,System Notification
161,3/31/2025 19:40,BillingSystem,System reboot initiated by user User819.,System Notification
163,6/6/2025 15:29,BillingSystem,System reboot initiated by user User938.,System Notification
307,4/12/2025 0:41,BillingSystem,System reboot initiated by user User929.,System Notification
365,10/20/2025 22:32,ModernHR,System reboot initiated by user User533.,System Notification
508,4/15/2025 2:04,ThirdPartyAPI,System reboot initiated by user User591.,System Notification
552,9/22/2025 20:54,ModernHR,System reboot initiated by user User421.,System Notification
668,9/5/2025 7:14,ModernHR,System reboot initiated by user User297.,System Notification
693,7/6/2025 21:40,BillingSystem,System reboot initiated by user User159.,System Notification
697,3/13/2025 7:09,BillingSystem,System reboot initiated by user User648.,System Notification
714,9/25/2025 23:35,ThirdPartyAPI,System reboot initiated by user User600.,System Notification
730,5/24/2025 11:08,AnalyticsEngine,System reboot initiated by user User120.,System Notification
800,8/15/2025 12:14,BillingSystem,System reboot initiated by user User901.,System Notification
837,4/9/2025 8:28,AnalyticsEngine,System reboot initiated by user User876.,System Notification
852,3/31/2025 5:20,ModernCRM,System reboot initiated by user User811.,System Notification
865,2/25/2025 1:40,AnalyticsEngine,System reboot initiated by user User964.,System Notification
889,11/30/2025 13:45,ModernHR,System reboot initiated by user User766.,System Notification
896,7/28/2025 11:24,BillingSystem,System reboot initiated by user User765.,System Notification
988,9/11/2025 22:23,BillingSystem,System reboot initiated by user User427.,System Notification
1106,12/28/2025 13:32,ModernHR,System reboot initiated by user User246.,System Notification
1159,8/5/2025 6:52,BillingSystem,System reboot initiated by user User329.,System Notification
1194,7/20/2025 9:10,AnalyticsEngine,System reboot initiated by user User747.,System Notification
1275,7/15/2025 23:37,BillingSystem,System reboot initiated by user User829.,System Notification
1299,7/15/2025 19:19,BillingSystem,System reboot initiated by user User966.,System Notification
1304,8/10/2025 6:18,ThirdPartyAPI,System reboot initiated by user User758.,System Notification
1524,11/30/2025 2:39,ThirdPartyAPI,System reboot initiated by user User278.,System Notification
1562,8/18/2025 4:17,ThirdPartyAPI,System reboot initiated by user User648.,System Notification
1624,12/14/2025 5:14,AnalyticsEngine,System reboot initiated by user User268.,System Notification
1663,10/27/2025 22:04,AnalyticsEngine,System reboot initiated by user User315.,System Notification
1776,2/21/2025 11:56,ModernHR,System reboot initiated by user User155.,System Notification
1803,8/22/2025 6:30,AnalyticsEngine,System reboot initiated by user User204.,System Notification
1804,8/26/2025 21:06,ModernHR,System reboot initiated by user User899.,System Notification
1852,1/26/2025 12:34,AnalyticsEngine,System reboot initiated by user User223.,System Notification
1865,5/11/2025 10:58,AnalyticsEngine,System reboot initiated by user User932.,System Notification
1956,9/26/2025 19:32,ThirdPartyAPI,System reboot initiated by user User264.,System Notification
2003,6/23/2025 17:54,ModernCRM,System reboot initiated by user User517.,System Notification
2014,12/25/2025 4:33,AnalyticsEngine,System reboot initiated by user User293.,System Notification
2043,9/12/2025 20:20,ThirdPartyAPI,System reboot initiated by user User262.,System Notification
2074,9/13/2025 8:43,ModernCRM,System reboot initiated by user User937.,System Notification
2228,9/3/2025 11:24,ModernHR,System reboot initiated by user User179.,System Notification
2243,1/16/2025 7:22,ModernHR,System reboot initiated by user User770.,System Notification
2246,3/2/2025 22:56,ModernHR,System reboot initiated by user User488.,System Notification
2253,10/7/2025 2:20,ModernHR,System reboot initiated by user User644.,System Notification
2317,3/7/2025 5:44,BillingSystem,System reboot initiated by user User724.,System Notification
2360,5/1/2025 4:21,ThirdPartyAPI,System reboot initiated by user User876.,System Notification

## Clusterning

In [48]:
from sklearn.cluster import DBSCAN

In [49]:
from sentence_transformers import SentenceTransformer

In [50]:
model= SentenceTransformer("all-MiniLM-L6-v2")

embeddings= model.encode(df['log_message'].tolist())

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9344.87it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [51]:
embeddings[0]

array([-1.02939673e-01,  3.35459784e-02, -2.20260806e-02,  1.55102601e-03,
       -9.86915827e-03, -1.78956300e-01, -6.34410828e-02, -6.01761751e-02,
        2.81108413e-02,  5.99619783e-02, -1.72618497e-02,  1.43372838e-03,
       -1.49560034e-01,  3.15285241e-03, -5.66031151e-02,  2.71685794e-02,
       -1.49890231e-02, -3.54038030e-02, -3.62936929e-02, -1.45410579e-02,
       -5.61500154e-03,  8.75538066e-02,  4.55120578e-02,  2.50964463e-02,
        1.00187277e-02,  1.24266697e-02, -1.39923573e-01,  7.68695846e-02,
        3.14095095e-02, -4.15249076e-03,  4.36902270e-02,  1.71250384e-02,
       -8.00950825e-02,  5.74005730e-02,  1.89091824e-02,  8.55261683e-02,
        3.96399498e-02, -1.34371817e-01, -1.44371425e-03,  3.06706317e-03,
        1.76854134e-01,  4.44883108e-03, -1.69274695e-02,  2.24266555e-02,
       -4.35050204e-02,  6.09027082e-03, -9.98169463e-03, -6.23972826e-02,
        1.07371965e-02, -6.04894804e-03, -7.14660361e-02, -8.45807511e-03,
       -3.18019465e-02, -1.00518353e-01,  2.25907352e-04, -1.89341269e-02,
       -3.17794383e-02,  4.00860831e-02,  2.19177566e-02, -2.59527899e-02,
        5.84525242e-02, -8.12509507e-02,  2.12028958e-02, -5.02687581e-02,
        1.32057471e-02,  1.32679078e-03,  2.27063671e-02, -3.45794037e-02,
        3.91547754e-02, -2.09433660e-02,  3.24819097e-03,  4.43960987e-02,
       -9.85357761e-02, -2.88895182e-02, -6.85030548e-03,  5.38819395e-02,
        6.46110177e-02, -2.45059934e-02,  9.21828747e-02, -7.49869794e-02,
        1.23995254e-02, -1.00026593e-01, -4.64910381e-02,  6.01570047e-02,
       -2.46480331e-02, -7.08075613e-02, -2.77270023e-02,  9.72611681e-02,
        3.85841541e-02, -1.44292749e-02, -7.46812962e-04, -1.04305129e-02,
       -1.61842573e-02,  4.43628132e-02,  9.25995875e-03,  7.14165494e-02,
        6.37917295e-02,  4.94931191e-02, -6.02567531e-02,  4.04806286e-02,
       -3.42860520e-02, -1.93881225e-02,  6.61233738e-02,  6.01589009e-02,
        1.09371012e-02, -5.38624683e-03,  1.44580035e-02,  9.25430208e-02,
       -3.14563550e-02, -1.84351318e-02,  9.91875678e-03, -1.85575280e-02,
        1.31282711e-03,  2.26852462e-05,  2.02731136e-03,  2.75256131e-02,
       -4.81927767e-02,  5.42825721e-02, -7.32067302e-02,  4.88667041e-02,
        4.98490706e-02, -9.01138503e-03, -4.68905866e-02, -4.25886735e-02,
       -8.19524005e-02,  3.87106389e-02,  7.85504058e-02,  1.46077096e-32,
        1.66707113e-02,  5.25493994e-02, -1.82449929e-02, -1.26686171e-02,
        6.52837008e-02, -2.11777817e-02, -4.06322554e-02,  4.14948389e-02,
       -2.48362143e-02, -1.33068105e-02, -5.46752885e-02, -5.99114515e-04,
       -4.89248661e-03, -6.27359822e-02, -3.84878442e-02, -6.13544136e-02,
        8.27405527e-02,  2.34380662e-02, -8.63082055e-03,  1.31002404e-02,
        6.44214377e-02, -4.41361815e-02, -6.98634461e-02, -7.36060068e-02,
       -4.33264114e-02,  6.96528843e-03, -5.05956300e-02, -1.60912182e-02,
       -5.66793717e-02,  3.35455779e-03,  5.34116141e-02,  2.47761216e-02,
       -1.47986449e-02, -2.93242522e-02,  7.30228424e-02, -1.86833385e-02,
        8.13136920e-02, -2.69967802e-02, -5.68055809e-02, -6.59388527e-02,
       -5.95394056e-03,  2.85312776e-02, -7.85358399e-02, -2.76695145e-03,
       -3.26476526e-03, -9.28333476e-02, -7.27363601e-02, -3.31903808e-02,
        1.01411127e-01,  9.79881436e-02, -9.78739932e-02,  1.98667962e-02,
        2.38836743e-02, -1.81672722e-02, -3.73708569e-02,  1.96562242e-03,
        6.34425879e-02,  1.18270377e-02, -1.12041291e-02, -3.87316085e-02,
        9.32424366e-02,  4.26632585e-03, -1.66872907e-02, -6.87464997e-02,
        1.55119505e-02, -4.97754514e-02,  3.34492438e-02,  8.00032094e-02,
        2.12281942e-02,  1.34581864e-01, -2.30730046e-02,  5.53858280e-02,
        3.07557955e-02, -2.93905586e-02,  2.31904965e-02, -9.34306756e-02,
        7.58034885e-02, -5.21202711e-03, -5.14523350e-02,  3.32689583e-02,
        3.67964022e-02, -1.06450990e-02,  1.01635261e-02, -2.07650922e-02,
       -5.85519150e-02,  4.79328893e-02,  2.13694945e-02,  8.76213461e-02,
        3.35485023e-03, -3.80336083e-02, -1.81205552e-02,  6.87445933e-03,
        5.15879355e-02, -4.75598276e-02, -6.12064786e-02, -1.45483604e-32,
        4.12804540e-03,  4.59641498e-03, -5.63901290e-02,  4.32473375e-03,
       -1.09447853e-03,  9.31952242e-03, -2.20268983e-02,  5.79565316e-02,
       -1.44787701e-02,  4.64156196e-02,  1.43542886e-01, -6.89756572e-02,
        6.09631054e-02, -8.93743932e-02,  2.40918845e-02,  2.06010100e-02,
       -2.82415710e-02, -6.48315996e-02,  5.64794801e-02, -7.48333754e-03,
       -3.52058560e-02,  8.51060078e-02,  1.30359363e-02,  2.02257857e-02,
       -1.44391125e-02, -4.63718399e-02,  1.77210439e-02,  1.59105211e-02,
       -9.51009318e-02, -3.54527868e-02,  2.08696052e-02,  3.84375360e-03,
       -8.77918079e-02,  6.44574910e-02,  1.44170923e-02,  3.84734897e-03,
        4.70991507e-02,  4.94662113e-02,  1.53862154e-02, -2.59578619e-02,
        9.10894945e-02,  1.83308218e-02, -5.89206666e-02,  2.51993034e-02,
       -3.30374502e-02,  8.23344812e-02,  1.74791720e-02,  6.48047104e-02,
       -1.19674206e-02, -3.31777930e-02,  3.00177522e-02,  3.54220346e-02,
       -1.39623927e-02,  6.69272915e-02,  3.87919880e-02,  6.06916919e-02,
        1.17960642e-03, -2.38786414e-02, -1.26930520e-01,  1.13846706e-02,
        1.59290321e-02, -1.29426541e-02, -8.63247737e-02,  8.53660051e-03,
        6.03760779e-02,  1.51121952e-02, -1.19132400e-01,  1.15234368e-02,
        5.97089380e-02, -3.93345617e-02,  1.55675085e-02,  1.04602491e-02,
       -4.72457446e-02, -2.59243809e-02,  9.98529606e-03,  3.07145845e-02,
       -7.14843944e-02,  6.98965136e-03, -1.55133493e-02,  2.18864568e-02,
       -2.78146192e-02,  6.92733899e-02, -2.75903922e-02,  2.62429286e-02,
        3.52562629e-02, -4.26419303e-02,  7.46331410e-04,  6.59866855e-02,
       -5.15104383e-02, -3.58434021e-02, -6.53446931e-03, -2.75858250e-02,
       -1.00125633e-01,  7.83325285e-02, -1.45799164e-02, -6.18457392e-08,
        2.00325325e-02,  6.59785643e-02, -2.04702783e-02,  1.64044406e-02,
        7.63001740e-02,  7.32182562e-02,  5.65787219e-03, -6.97739015e-04,
       -3.63799417e-03,  6.02394938e-02, -3.27187516e-02, -6.45837858e-02,
       -5.97953573e-02, -1.76696386e-02,  6.10141084e-03, -5.63489227e-03,
       -1.22972228e-01,  6.35818690e-02, -2.19432004e-02, -1.16406530e-01,
        2.34365240e-02, -7.23524913e-02,  2.31774226e-02, -6.55987561e-02,
       -7.42682368e-02,  2.60146186e-02,  3.59758101e-02,  7.68432915e-02,
       -3.08057368e-02, -2.34793723e-02, -6.30426109e-02, -3.62157784e-02,
       -1.03560118e-02, -4.75603230e-02, -2.87521686e-02,  2.96401102e-02,
       -5.26901567e-03,  5.67890070e-02, -3.74485739e-03,  3.09612118e-02,
        3.48227248e-02,  3.78607735e-02,  2.10155714e-02,  2.70691682e-02,
        5.25521301e-02,  7.16229454e-02, -5.53757232e-03,  4.01093811e-02,
        5.16276099e-02, -2.67314725e-02,  5.94224446e-02, -4.29224335e-02,
       -1.19760633e-02,  3.05985995e-02, -7.40331709e-02,  1.84221882e-02,
       -8.64856876e-03, -8.83558542e-02, -5.91984428e-02, -1.00879726e-04,
        1.12913609e-01,  4.57781693e-03, -4.25971746e-02,  3.22624668e-03],
      dtype=float32)

In [52]:
len(embeddings[0])

384

In [53]:
clustering= DBSCAN(eps=0.2, min_samples=1, metric= "cosine").fit(embeddings)

df['cluster']= clustering.labels_

In [54]:
df.head(10)

,timestamp,source,log_message,target_label,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0
5,2025-10-09 10:30:31,ModernHR,nova.osapi_compute.wsgi.server [req-f0bffbc3-5...,HTTP Status,0
6,3/1/2025 19:14,ModernHR,Shard 6 replication task ended in failure,Error,3
7,10/11/2025 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,4
8,2025-02-12 10:42:29,ThirdPartyAPI,nova.compute.claims [req-a07ac654-8e81-416d-bf...,Resource Usage,5
9,2025-03-30 04:01:45,ModernHR,nova.osapi_compute.wsgi.server [req-2bf7cfee-a...,HTTP Status,0

In [55]:
df.tail(10)

,timestamp,source,log_message,target_label,cluster
2400,2025-01-07 09:13:28,ThirdPartyAPI,nova.compute.resource_tracker [req-addc1839-2e...,Resource Usage,10
2401,2025-12-05 15:51:51,ModernCRM,nova.osapi_compute.wsgi.server [req-4bdf00b0-3...,HTTP Status,0
2402,3/13/2025 9:44,BillingSystem,Replication error occurred for shard 10,Error,3
2403,10/1/2025 1:31,ModernCRM,Backup completed successfully.,System Notification,8
2404,2025-09-18 02:18:30,ThirdPartyAPI,nova.osapi_compute.wsgi.server [req-2c9c783f-3...,HTTP Status,0
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,7
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,7

In [56]:
clusters= df.groupby('cluster')['log_message'].apply(list)
sorted_cluster= clusters.sort_values(key= lambda x: x.map(len), ascending=False)

In [57]:
print("Cluster Pattern")
for cluster_id, messages in sorted_cluster.items():
    if len(messages)>10:
        print(f"cluster id {cluster_id}:")
        for msg in messages[0:10]:
            print(f" {msg}")

Cluster Pattern
cluster id 0:
 nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
 nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
 nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
 nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
 nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369
 nova.osapi_compute.wsgi.server [req-d4f8d0c2-4f21-4b38-9f85-d82f8da75c23 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2663860
 nova.osapi_compute.wsgi.server [req-6fe0e366-f20b-454e-ade1-771deb7a911f 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Status code -  200 len: 1893 time: 0.2608259
 nova.osapi_compute.wsgi.server [req-5f1c2027-e1b0-43f1-b6d3-694f483a69be 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1893 time: 0.2732208
 nova.osapi_compute.wsgi.server [req-945d1f31-a2e5-496a-a1da-21a0c88b6b61 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 1893 time: 0.2775040
 nova.osapi_compute.wsgi.server [req-033d97b9-69e4-4acd-9029-f0d7b9370645 f7b8d1f1d4d44643b07fa10ca7d021fb e9746973ac574c6b8a9e8857f56a7608 - - -] 10.11.10.1 "POST /v2/e9746973ac574c6b8a9e8857f56a7608/os-server-external-events HTTP/1.1" status: 404 len: 296 time: 0.0847020
cluster id 5:
 nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
 nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
 nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
 nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
 nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited
 nova.compute.claims [req-d82fab16-60f8-4c9f-bde8-f362f57bdd40 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: ae3a1b5d-eec1-45bb-b76a-c59d83b1471f] memory limit: 96258.00 MB, free: 95746.00 MB
 nova.compute.claims [req-868a5460-dbb6-416b-b4c4-a98abae6c847 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 17288ea8-cbf4-4f0e-94fe-853fd2735f29] Total vcpu: 16 VCPU, used: 0.00 VCPU
 nova.compute.claims [req-2d658d2c-7eff-414e-a68f-3f1c75c9e874 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 7e7cc42f-3cb9-4d91-804c-f5a32d54f1c5] Total disk: 15 GB, used: 0.00 GB
 nova.compute.claims [req-29a09cdb-3169-4c40-8bd1-552636286362 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 43204226-2f87-4da7-b7ee-4d20cc66e846] Total vcpu: 16 VCPU, used: 0.00 VCPU
 nova.compute.claims [req-9118475d-6e72-48fa-9dee-e6b7d957dcd6 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: be793e89-2cc3-4f99-9884-9c6a624a84bc] Attempting claim: memory 2048 MB, disk 20 GB, vcpus 1 CPU
cluster id 11:
 User User685 logged out.
 User User395 logged in.
 User User225 logged in.
 User User494 logged out.
 User User900 logged in.
 User User272 logged out.
 User User706 logged out.
 User User881 logged out.
 User User313 logged out.
 User User641 logged out.
cluster id 13:
 Backup started at 2025-05-14 07:06:55.
 Backup started at 2025-02-15 20:00:19.
 Backup ended at 2025-08-08 13:06:23.
 Backup started at 2025-11-14 08:27:43.
 Backup started at 2025-12-09 10:19:11.
 Backup started at 2025-01-15 04:36:39.
 Backup started at 2025-08-29 15:17:18.
 Backup ended at 2025-06-01 06:27:38.
 Backup ended at 2025-11-16 08:17:13.
 Backup ended at 2025-07-18 17:06:54.
cluster id 7:
 Multiple bad login attempts detected on user 8538 account
 Multiple login failures occurred on user 9052 account
 User 7153 made multiple incorrect login attempts
 User 8300 made multiple incorrect login attempts
 Multiple login failures were detected for user 6373
 Multiple failed login attempts were reported for user 1053
 Multiple incorrect login attempts were made by user 7918
 User 9167 experienced repeated login failures
 Repeated failed login attempts occurred for user ID 8527
 User 9131 made multiple failed login attempts
cluster id 8:
 Backup completed successfully.
 Backup completed successfully.
 Backup completed successfully.
 Backup completed successfully.
 Backup completed successfully.
 Backup completed successfully.
 Backup completed successfully.
 Backup completed successfully.
 Backup completed successfully.
 Backup completed successfully.
cluster id 21:
 System updated to version 3.9.1.
 System updated to version 5.5.4.
 System updated to version 4.7.4.
 System updated to version 3.7.7.
 System updated to version 2.6.2.
 System updated to version 3.8.2.
 System updated to version 1.9.3.
 System updated to version 4.8.6.
 System updated to version 5.0.7.
 System updated to version 1.2.9.
cluster id 3:
 Shard 6 replication task ended in failure
 Data replication task for shard 14 did not complete
 Data replication task failed for shard 17
 Replication of data to shard 14 failed
 Data replication task for shard 6 did not complete
 Shard 1 data copy failed
 Data replication for shard 13 encountered an issue
 Shard 8 synchronization task failed
 Data replication for shard 16 was unsuccessful
 Shard 2 experienced a replication failure
cluster id 4:
 File data_6169.csv uploaded successfully by user User953.
 File data_3847.csv uploaded successfully by user User175.
 File data_7366.csv uploaded successfully by user User282.
 File data_1206.csv uploaded successfully by user User359.
 File data_1503.csv uploaded successfully by user User151.
 File data_2127.csv uploaded successfully by user User577.
 File data_9318.csv uploaded successfully by user User917.
 File data_5435.csv uploaded successfully by user User563.
 File data_4085.csv uploaded successfully by user User222.
 File data_7222.csv uploaded successfully by user User296.
cluster id 17:
 Denied access attempt on restricted account Account2682
 Unauthorized login attempt on protected account Account5030
 Account Account9437 blocked due to failed login
 Account Account7999 access denied due to login failure
 Invalid login attempt made on secured account Account7864
 Account Account8057 login attempt was not successful
 Invalid login attempt made on secured account Account8771
 Restricted account Account9226 had login failure
 Account Account9938 blocked due to failed login
 Login to secured account Account6057 was not possible
cluster id 32:
 Disk cleanup completed successfully.
 Disk cleanup completed successfully.
 Disk cleanup completed successfully.
 Disk cleanup completed successfully.
 Disk cleanup completed successfully.
 Disk cleanup completed successfully.
 Disk cleanup completed successfully.
 Disk cleanup completed successfully.
 Disk cleanup completed successfully.
 Disk cleanup completed successfully.
cluster id 6:
 Critical system unit error: unit ID Component55
 System component malfunction: component ID Component79
 Critical system element is down: element ID Component96
 Essential system part malfunction: part ID Component6
 Failure occurred in critical system component: component ID Component92
 Essential system part malfunction: part ID Component97
 System component malfunction: component ID Component90
 Failure of critical system component: component ID Component54
 System component has stopped working: component ID Component51
 Critical system equipment failure: equipment ID Component68
cluster id 16:
 System reboot initiated by user User243.
 System reboot initiated by user User471.
 System reboot initiated by user User216.
 System reboot initiated by user User639.
 System reboot initiated by user User819.
 System reboot initiated by user User938.
 System reboot initiated by user User929.
 System reboot initiated by user User533.
 System reboot initiated by user User591.
 System reboot initiated by user User421.
cluster id 20:
 User 7662 tried to bypass API security measures
 User 2367 failed to provide valid API access credentials
 User 3569 made an unauthorized API request
 Unauthorized user 2968 tried to access restricted API
 User 2186 attempted to access API without proper authorization
 Unapproved API login attempt from user 1618 recorded
 Security alert: unauthorized API access attempt by user 9816
 Unapproved API login attempt from user 5771 recorded
 Unauthenticated API access attempt from user 7672 logged
 API access denied due to unauthorized credentials for user 7900
cluster id 9:
 Account with ID 5351 created by User634.
 Account with ID 7813 created by User373.
 Account with ID 9827 created by User965.
 Account with ID 2520 created by User546.
 Account with ID 2300 created by User964.
 Account with ID 7505 created by User322.
 Account with ID 4810 created by User581.
 Account with ID 4995 created by User559.
 Account with ID 3889 created by User852.
 Account with ID 1478 created by User605.
cluster id 1:
 Email service experiencing issues with sending
 Email server encountered a sending fault
 Mail service encountered a delivery glitch
 Service disruption caused by email sending error
 Email system had a problem sending emails
 Email service experienced a sending issue
 Email delivery system encountered an error
 Email transmission error caused service impact
 Email service impacted by sending failure
 Email delivery problem affected system
cluster id 10:
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 1
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
 nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
cluster id 34:
 Abnormal behavior found on server 10, possible security threat
 Security alert: suspicious activity on server 1
 Anomalous activity identified on server 23, security review recommended
 Server 27 experienced potential security incident, review required
 Server 36 experienced potential security incident, review required
 Security alert: suspicious activity on server 31
 Abnormal behavior found on server 50, possible security threat
 Server 31 has been flagged for suspicious activity, security review
 Server 46 has been compromised, potential security risk
 Security issue detected on server 23, investigation required
cluster id 14:
 Detection of multiple disk faults in RAID setup
 RAID array suffered multiple hard drive failures
 RAID array experienced multiple disk crashes
 Multiple hard drive issues in RAID configuration found
 Identification of multiple faulty disks in RAID array
 RAID system detected multiple disk failures and errors
 RAID system reported multiple hard drive malfunctions
 RAID configuration had multiple disk failures detected
 Multiple disk errors found in RAID configuration
 RAID array experienced multiple disk failures and issues
cluster id 53:
 Module X experienced an invalid data format issue
 Input format mismatch occurred in module X
 Module X reported an error in input format validation
 Module X failed to process input due to formatting error
 Input data format in module X was invalid or corrupted
 Input to module X did not conform to expected format
 Format of input data in module X was not recognized
 Error in input format occurred during module X execution
 Invalid input format caused module X to fail
 Input to module X was not in the expected format
cluster id 52:
 Service health check was not successful because of SSL certificate validation failures.
 Invalid SSL certificate resulted in a failed service health check.
 Service health check failure was due to an invalid or improperly configured SSL certificate.
 An issue with the SSL certificate caused the service health check to fail.
 Service health check failure was caused by an expired SSL certificate.
 SSL certificate validation errors resulted in a failed service health check.
 The service health check could not complete due to an SSL certificate issue.
 Service health check was unsuccessful due to an invalid SSL certification.
 Invalid SSL certificate configuration led to a failed service health check.
 SSL certificate validation issues caused the service health check to be unsuccessful.
cluster id 18:
 Boot process terminated unexpectedly due to kernel issue
 System encountered kernel panic during initialization phase
 Boot process was stopped by kernel malfunction
 System encountered kernel failure during bootup sequence
 Boot sequence failed due to kernel panic
 System boot was halted by kernel issue
 Kernel issue prevented system from booting correctly
 System crash happened due to kernel problem during boot
 Kernel panic terminated system boot sequence
 Kernel error terminated boot process prematurely
cluster id 25:
 System configuration is no longer valid
 Configuration is corrupted throughout the system
 Cross-system configuration failure occurred
 System configuration is experiencing errors
 Configuration malfunction is system-wide
 Entire system configuration is faulty
 System configuration errors have been detected
 System configuration has been severely damaged
 System-wide configuration failure has occurred
 System configuration files are corrupted
cluster id 42:
 User 5127 has escalated admin privileges without authorization
 User 9745 has escalated to admin level
 User 8483 escalated privileges to admin level
 User 1987 has escalated to admin level
 User 8395 escalated privileges to admin level
 User 8693 has escalated to admin level
 User 9202 has admin privileges escalated
 User 4373 has escalated admin privileges without authorization
 Unauthorized admin privilege escalation by user 3332
 User 1985 has admin privileges escalated
cluster id 59:
 Potential security threat: Admin privilege escalation for user 5130
 Admin privilege escalation alert for user 2893
 Admin privilege escalation alert for user 8532
 Potential security threat: Admin privilege escalation for user 1554
 Warning: Potential admin privilege escalation for user 5720
 Alert: Admin privilege escalation for user 6856 detected
 Alert: Admin privilege escalation for user 5721 detected
 Warning: Potential admin privilege escalation for user 5706
 Alert: Admin privilege escalation for user 9724 detected
 Warning: Potential admin privilege escalation for user 1559
cluster id 26:
 Privilege elevation detected for user 5038
 Elevation of admin privileges detected for user 6137
 Elevation of admin privileges detected for user 4907
 User 6069 has been granted elevated admin privileges
 Admin privilege elevation warning for user 7574
 Privilege elevation detected for user 6942
 Elevation of admin privileges detected for user 8436
 Privilege elevation detected for user 3965
 Admin rights elevated for user 6519
 Admin privilege elevation warning for user 8383

## Stage-1 Classifier: Regex

In [58]:
import re

def classifiy_with_regex(log_message):
    regex_patterns= {
        r"(U|u)ser (U|u)ser\d+ logged (in|out)": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }

    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message):
            return label
    return None

In [59]:
classifiy_with_regex("User user888983738 logged in.")

'User Action'

In [60]:
classifiy_with_regex("Hey my name is Sachin")

In [61]:
df['regex_label']= df['log_message'].apply(lambda x: classifiy_with_regex(x))

In [62]:
df

,timestamp,source,log_message,target_label,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,None
...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0,None
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,7,None

In [63]:
df[df['regex_label'].notnull()]

,timestamp,source,log_message,target_label,cluster,regex_label
7,10/11/2025 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,4,System Notification
14,1/4/2025 1:43,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,4,System Notification
15,5/1/2025 9:41,ModernCRM,Backup completed successfully.,System Notification,8,System Notification
18,2/22/2025 17:49,ModernCRM,Account with ID 5351 created by User634.,User Action,9,User Action
27,9/24/2025 19:57,ThirdPartyAPI,User User685 logged out.,User Action,11,User Action
...,...,...,...,...,...,...
2376,6/27/2025 8:47,ModernCRM,System updated to version 2.0.5.,System Notification,21,System Notification
2381,9/5/2025 6:39,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,32,System Notification
2394,4/3/2025 13:13,ModernHR,Disk cleanup completed successfully.,System Notification,32,System Notification
2395,5/2/2025 14:29,ThirdPartyAPI,Backup ended at 2025-05-06 11:23:16.,System Notification,13,System Notification
2403,10/1/2025 1:31,ModernCRM,Backup completed successfully.,System Notification,8,System Notification

In [64]:
df[df['regex_label'].isna()]

,timestamp,source,log_message,target_label,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,None
...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0,None
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,7,None

## Stage-2 Classification- using embedding model

In [65]:
df_non_regex= df[df['regex_label'].isnull()].copy()
df_non_regex

,timestamp,source,log_message,target_label,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,None
...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0,None
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,7,None

In [66]:
df_legacy= df_non_regex[df_non_regex.source=="LegacyCRM"]
df_legacy

,timestamp,source,log_message,target_label,cluster,regex_label
60,2025-10-06 16:55:23,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error,24,None
255,2025-05-03 16:55:35,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning,48,None
377,2025-06-24 12:16:29,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error,62,None
1325,2025-04-17 07:33:44,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error,105,None
1734,2025-04-30 07:47:30,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning,118,None
1826,2025-01-23 10:33:36,LegacyCRM,Support for legacy authentication methods will...,Deprecation Warning,122,None
2217,2025-05-12 09:46:54,LegacyCRM,Task assignment for TeamID 3425 could not comp...,Workflow Error,133,None

In [67]:
df_non_legacy= df_non_regex[df_non_regex.source!="LegacyCRM"]
df_non_legacy

,timestamp,source,log_message,target_label,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,None
...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0,None
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,7,None

In [68]:
model= SentenceTransformer("all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 13733.89it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [69]:
embeddings_filtered = model.encode(df_non_legacy['log_message'].to_list())

In [70]:
embeddings_filtered[0]

array([-1.02939673e-01,  3.35459784e-02, -2.20260806e-02,  1.55102601e-03,
       -9.86915827e-03, -1.78956300e-01, -6.34410828e-02, -6.01761751e-02,
        2.81108413e-02,  5.99619783e-02, -1.72618497e-02,  1.43372838e-03,
       -1.49560034e-01,  3.15285241e-03, -5.66031151e-02,  2.71685794e-02,
       -1.49890231e-02, -3.54038030e-02, -3.62936929e-02, -1.45410579e-02,
       -5.61500154e-03,  8.75538066e-02,  4.55120578e-02,  2.50964463e-02,
        1.00187277e-02,  1.24266697e-02, -1.39923573e-01,  7.68695846e-02,
        3.14095095e-02, -4.15249076e-03,  4.36902270e-02,  1.71250384e-02,
       -8.00950825e-02,  5.74005730e-02,  1.89091824e-02,  8.55261683e-02,
        3.96399498e-02, -1.34371817e-01, -1.44371425e-03,  3.06706317e-03,
        1.76854134e-01,  4.44883108e-03, -1.69274695e-02,  2.24266555e-02,
       -4.35050204e-02,  6.09027082e-03, -9.98169463e-03, -6.23972826e-02,
        1.07371965e-02, -6.04894804e-03, -7.14660361e-02, -8.45807511e-03,
       -3.18019465e-02, -1.00518353e-01,  2.25907352e-04, -1.89341269e-02,
       -3.17794383e-02,  4.00860831e-02,  2.19177566e-02, -2.59527899e-02,
        5.84525242e-02, -8.12509507e-02,  2.12028958e-02, -5.02687581e-02,
        1.32057471e-02,  1.32679078e-03,  2.27063671e-02, -3.45794037e-02,
        3.91547754e-02, -2.09433660e-02,  3.24819097e-03,  4.43960987e-02,
       -9.85357761e-02, -2.88895182e-02, -6.85030548e-03,  5.38819395e-02,
        6.46110177e-02, -2.45059934e-02,  9.21828747e-02, -7.49869794e-02,
        1.23995254e-02, -1.00026593e-01, -4.64910381e-02,  6.01570047e-02,
       -2.46480331e-02, -7.08075613e-02, -2.77270023e-02,  9.72611681e-02,
        3.85841541e-02, -1.44292749e-02, -7.46812962e-04, -1.04305129e-02,
       -1.61842573e-02,  4.43628132e-02,  9.25995875e-03,  7.14165494e-02,
        6.37917295e-02,  4.94931191e-02, -6.02567531e-02,  4.04806286e-02,
       -3.42860520e-02, -1.93881225e-02,  6.61233738e-02,  6.01589009e-02,
        1.09371012e-02, -5.38624683e-03,  1.44580035e-02,  9.25430208e-02,
       -3.14563550e-02, -1.84351318e-02,  9.91875678e-03, -1.85575280e-02,
        1.31282711e-03,  2.26852462e-05,  2.02731136e-03,  2.75256131e-02,
       -4.81927767e-02,  5.42825721e-02, -7.32067302e-02,  4.88667041e-02,
        4.98490706e-02, -9.01138503e-03, -4.68905866e-02, -4.25886735e-02,
       -8.19524005e-02,  3.87106389e-02,  7.85504058e-02,  1.46077096e-32,
        1.66707113e-02,  5.25493994e-02, -1.82449929e-02, -1.26686171e-02,
        6.52837008e-02, -2.11777817e-02, -4.06322554e-02,  4.14948389e-02,
       -2.48362143e-02, -1.33068105e-02, -5.46752885e-02, -5.99114515e-04,
       -4.89248661e-03, -6.27359822e-02, -3.84878442e-02, -6.13544136e-02,
        8.27405527e-02,  2.34380662e-02, -8.63082055e-03,  1.31002404e-02,
        6.44214377e-02, -4.41361815e-02, -6.98634461e-02, -7.36060068e-02,
       -4.33264114e-02,  6.96528843e-03, -5.05956300e-02, -1.60912182e-02,
       -5.66793717e-02,  3.35455779e-03,  5.34116141e-02,  2.47761216e-02,
       -1.47986449e-02, -2.93242522e-02,  7.30228424e-02, -1.86833385e-02,
        8.13136920e-02, -2.69967802e-02, -5.68055809e-02, -6.59388527e-02,
       -5.95394056e-03,  2.85312776e-02, -7.85358399e-02, -2.76695145e-03,
       -3.26476526e-03, -9.28333476e-02, -7.27363601e-02, -3.31903808e-02,
        1.01411127e-01,  9.79881436e-02, -9.78739932e-02,  1.98667962e-02,
        2.38836743e-02, -1.81672722e-02, -3.73708569e-02,  1.96562242e-03,
        6.34425879e-02,  1.18270377e-02, -1.12041291e-02, -3.87316085e-02,
        9.32424366e-02,  4.26632585e-03, -1.66872907e-02, -6.87464997e-02,
        1.55119505e-02, -4.97754514e-02,  3.34492438e-02,  8.00032094e-02,
        2.12281942e-02,  1.34581864e-01, -2.30730046e-02,  5.53858280e-02,
        3.07557955e-02, -2.93905586e-02,  2.31904965e-02, -9.34306756e-02,
        7.58034885e-02, -5.21202711e-03, -5.14523350e-02,  3.32689583e-02,
        3.67964022e-02, -1.06450990e-02,  1.01635261e-02, -2.07650922e-02,
       -5.85519150e-02,  4.79328893e-02,  2.13694945e-02,  8.76213461e-02,
        3.35485023e-03, -3.80336083e-02, -1.81205552e-02,  6.87445933e-03,
        5.15879355e-02, -4.75598276e-02, -6.12064786e-02, -1.45483604e-32,
        4.12804540e-03,  4.59641498e-03, -5.63901290e-02,  4.32473375e-03,
       -1.09447853e-03,  9.31952242e-03, -2.20268983e-02,  5.79565316e-02,
       -1.44787701e-02,  4.64156196e-02,  1.43542886e-01, -6.89756572e-02,
        6.09631054e-02, -8.93743932e-02,  2.40918845e-02,  2.06010100e-02,
       -2.82415710e-02, -6.48315996e-02,  5.64794801e-02, -7.48333754e-03,
       -3.52058560e-02,  8.51060078e-02,  1.30359363e-02,  2.02257857e-02,
       -1.44391125e-02, -4.63718399e-02,  1.77210439e-02,  1.59105211e-02,
       -9.51009318e-02, -3.54527868e-02,  2.08696052e-02,  3.84375360e-03,
       -8.77918079e-02,  6.44574910e-02,  1.44170923e-02,  3.84734897e-03,
        4.70991507e-02,  4.94662113e-02,  1.53862154e-02, -2.59578619e-02,
        9.10894945e-02,  1.83308218e-02, -5.89206666e-02,  2.51993034e-02,
       -3.30374502e-02,  8.23344812e-02,  1.74791720e-02,  6.48047104e-02,
       -1.19674206e-02, -3.31777930e-02,  3.00177522e-02,  3.54220346e-02,
       -1.39623927e-02,  6.69272915e-02,  3.87919880e-02,  6.06916919e-02,
        1.17960642e-03, -2.38786414e-02, -1.26930520e-01,  1.13846706e-02,
        1.59290321e-02, -1.29426541e-02, -8.63247737e-02,  8.53660051e-03,
        6.03760779e-02,  1.51121952e-02, -1.19132400e-01,  1.15234368e-02,
        5.97089380e-02, -3.93345617e-02,  1.55675085e-02,  1.04602491e-02,
       -4.72457446e-02, -2.59243809e-02,  9.98529606e-03,  3.07145845e-02,
       -7.14843944e-02,  6.98965136e-03, -1.55133493e-02,  2.18864568e-02,
       -2.78146192e-02,  6.92733899e-02, -2.75903922e-02,  2.62429286e-02,
        3.52562629e-02, -4.26419303e-02,  7.46331410e-04,  6.59866855e-02,
       -5.15104383e-02, -3.58434021e-02, -6.53446931e-03, -2.75858250e-02,
       -1.00125633e-01,  7.83325285e-02, -1.45799164e-02, -6.18457392e-08,
        2.00325325e-02,  6.59785643e-02, -2.04702783e-02,  1.64044406e-02,
        7.63001740e-02,  7.32182562e-02,  5.65787219e-03, -6.97739015e-04,
       -3.63799417e-03,  6.02394938e-02, -3.27187516e-02, -6.45837858e-02,
       -5.97953573e-02, -1.76696386e-02,  6.10141084e-03, -5.63489227e-03,
       -1.22972228e-01,  6.35818690e-02, -2.19432004e-02, -1.16406530e-01,
        2.34365240e-02, -7.23524913e-02,  2.31774226e-02, -6.55987561e-02,
       -7.42682368e-02,  2.60146186e-02,  3.59758101e-02,  7.68432915e-02,
       -3.08057368e-02, -2.34793723e-02, -6.30426109e-02, -3.62157784e-02,
       -1.03560118e-02, -4.75603230e-02, -2.87521686e-02,  2.96401102e-02,
       -5.26901567e-03,  5.67890070e-02, -3.74485739e-03,  3.09612118e-02,
        3.48227248e-02,  3.78607735e-02,  2.10155714e-02,  2.70691682e-02,
        5.25521301e-02,  7.16229454e-02, -5.53757232e-03,  4.01093811e-02,
        5.16276099e-02, -2.67314725e-02,  5.94224446e-02, -4.29224335e-02,
       -1.19760633e-02,  3.05985995e-02, -7.40331709e-02,  1.84221882e-02,
       -8.64856876e-03, -8.83558542e-02, -5.91984428e-02, -1.00879726e-04,
        1.12913609e-01,  4.57781693e-03, -4.25971746e-02,  3.22624668e-03],
      dtype=float32)

In [71]:
len(embeddings_filtered[0])

384

In [72]:
# X= embeddings_filtered
# y= df_non_legacy['target_label'].values

X = embeddings_filtered
y = df_non_legacy['target_label'].to_numpy()

In [73]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [74]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=42)
clf= LogisticRegression(max_iter=1000)

In [75]:
clf.fit(X_train,y_train)
y_pred= clf.predict(X_test)

report= classification_report(y_test, y_pred)

print(report)

                precision    recall  f1-score   support

Critical Error       0.92      1.00      0.96        35
         Error       0.96      0.89      0.92        27
   HTTP Status       1.00      1.00      1.00       197
Resource Usage       1.00      1.00      1.00        35
Security Alert       1.00      0.99      0.99        87

      accuracy                           0.99       381
     macro avg       0.98      0.98      0.98       381
  weighted avg       0.99      0.99      0.99       381

In [76]:
import joblib

joblib.dump(clf, "log_classifier.joblib")

['log_classifier.joblib']

## MLflow Tracking — Log to DagsHub
Logs parameters, metrics, and the trained model to the DagsHub remote MLflow tracking server.

In [77]:
import mlflow
import mlflow.sklearn

import dagshub

from sklearn.metrics import classification_report, accuracy_score

In [78]:
dagshub.init(repo_owner="SachinMishra-ux",
            repo_name= "log_classifier_project_2",
            mlflow=True)

Initialized MLflow to track repo "SachinMishra-ux/log_classifier_project_2"

Repository SachinMishra-ux/log_classifier_project_2 initialized!

In [79]:
mlflow.set_experiment('experiment1')

with mlflow.start_run(run_name="Log_Logistic") as run:

    # ✅ log_param (singular) for individual key-value pairs
    mlflow.log_param('model_type', 'LogisticRegression')
    mlflow.log_param('embedding_model', 'all-MiniLM-L6-v2')
    mlflow.log_param('embedding_dim', '384')
    mlflow.log_param('max_iter', 1000)
    mlflow.log_param('test_size', 0.2)
    mlflow.log_param('random_state', 42)

    # metrics:
    report_dict = classification_report(y_test, y_pred, output_dict=True)

    mlflow.log_metric('accuracy', report_dict['accuracy'])
    mlflow.log_metric('macro_precision', report_dict['macro avg']['precision'])
    mlflow.log_metric('macro_recall', report_dict['macro avg']['recall'])
    mlflow.log_metric('macro_f1', report_dict['macro avg']['f1-score'])

    for label in report_dict:
        if label not in ('accuracy', 'macro avg', 'weighted avg'):
            safe = label.replace(' ', '_')
            mlflow.log_metric(f"{safe}_precision", report_dict[label]['precision'])
            mlflow.log_metric(f"{safe}_recall", report_dict[label]['recall'])
            mlflow.log_metric(f"{safe}_f1", report_dict[label]['f1-score'])

    mlflow.sklearn.log_model(clf, artifact_path="log_classifier_model")

    # ✅ Capture run_id INSIDE the with block while run is still active
    run_id = run.info.run_id

print(f"Run id: {run_id}")
print(f"Report Dict: {report_dict}")

2026/04/22 16:39:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/22 16:39:30 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run Log_Logistic at: https://dagshub.com/SachinMishra-ux/log_classifier_project_2.mlflow/#/experiments/0/runs/8e189e64afd040d59509d7bc5d40fdc7
🧪 View experiment at: https://dagshub.com/SachinMishra-ux/log_classifier_project_2.mlflow/#/experiments/0
Run id: 8e189e64afd040d59509d7bc5d40fdc7
Report Dict: {'Critical Error': {'precision': 0.9210526315789473, 'recall': 1.0, 'f1-score': 0.958904109589041, 'support': 35.0}, 'Error': {'precision': 0.96, 'recall': 0.8888888888888888, 'f1-score': 0.9230769230769231, 'support': 27.0}, 'HTTP Status': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 197.0}, 'Resource Usage': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 35.0}, 'Security Alert': {'precision': 1.0, 'recall': 0.9885057471264368, 'f1-score': 0.9942196531791907, 'support': 87.0}, 'accuracy': 0.989501312335958, 'macro avg': {'precision': 0.9762105263157895, 'recall': 0.9754789272030651, 'f1-score': 0.9752401371690309, 'support': 381.0}, 'weighted avg': {'precision': 0.9899129714048901, 'recall': 0.989501312335958, 'f1-score': 0.9894536235834199, 'support': 381.0}}